name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run tests with pytest
      run: |
        python -m pytest src/tests/ -v --tb=short
    
    - name: Run comprehensive YAML validation test
      run: |
        python src/tests/test_yaml_validation.py
    
    - name: Run linting
      run: |
        python -m flake8 src/gdx_config_validator/ --max-line-length=100 --ignore=E203,W503 --statistics
      continue-on-error: true